version: "3"
# FIND&REPLACE ALL "domain.url" to your domain
# FIND&REPLACE ALL "domain.url.conf" to your domain
# FIND&REPLACE ALL "#-" to "-"
services:
  php-fpm:
    image: php:fpm-alpine
    volumes:
      - ./src/localhost/www:/usr/share/nginx/www  # Ip Doc
      #- ./src/domain.url/www:/usr/share/nginx/domain.url/www  # Web Doc
    command: /bin/sh -c "docker-php-ext-install mysqli"
    restart: always
  nginx:
    image: nginx:alpine
    volumes:
      #- ./config/sites-conf/default.conf:/etc/nginx/sites-conf/default.conf
      #- ./config/sites-conf/domain.url.conf:/etc/nginx/sites-conf/domain.url.conf

      - ./config/nginx.conf:/etc/nginx/nginx.conf  # Default Config	
      - ./config/sites-conf:/etc/nginx/sites-conf  # Nginx Config Folder

      - ./src/localhost/www:/usr/share/nginx/www  # Ip Doc
      #- ./src/domain.url/www:/usr/share/nginx/domain.url/www  # Web Doc
      
      #- ./etc/ssl:/etc/nginx/etc/ssl  # SSL Certificates
      
    ports:
      - "8000:80"
    depends_on:
      - php-fpm
    restart: always
    
  mariadb:
    image: mariadb  # 120mb
    expose:
      - "3306"
    environment:
      MARIADB_ROOT_PASSWORD: 1 #change password
    restart: always
    
  #phpmyadmin:
    #image: phpmyadmin
    #ports:
      #- "8082:80"
    #environment:
      #PMA_ARBITRARY: 1
    #restart: always
